app/barber/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField, IntegerField
from wtforms.validators import DataRequired, EqualTo, ValidationError, Length
from app.models import Barber


class NewBarberForm(FlaskForm):
    first_name = StringField('First Name', validators=[DataRequired()])
    last_name = StringField('Last Name', validators=[DataRequired()])
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    password2 = PasswordField('Repeat Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Add barber')

    def validate_username(self, username):
        user = Barber.query.filter_by(username=username.data).first()
        if user is not None:
            raise ValidationError('Please use a different username.')


class NewServiceForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    description = TextAreaField('Description', validators=[DataRequired(), Length(min=0, max=300)])
    duration = IntegerField('Duration (minutes)', validators=[DataRequired()])
    price = IntegerField('Price (RON)', validators=[DataRequired()])
    submit = SubmitField('Add service')

app/barber/__init__.py
from flask import Blueprint

bp = Blueprint('barber', __name__)

from app.barber import routes

app/barber/routes.py
from app.barber import bp
from app.barber.forms import NewBarberForm, NewServiceForm
from app.models import Barber, Service
from app import db
from flask import render_template, redirect, flash, url_for
from flask_login import login_required, current_user
from datetime import date


@bp.route('/', methods=['GET', 'POST'])
@bp.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    if current_user.username == 'admin':
        new_barber_form = NewBarberForm()
        if new_barber_form.validate_on_submit():
            barber = Barber(first_name=new_barber_form.first_name.data,
                            last_name=new_barber_form.last_name.data,
                            username=new_barber_form.username.data)
            barber.set_password(new_barber_form.password.data)
            db.session.add(barber)
            db.session.commit()
            flash('{} {} is now registered as a barber!'.format(new_barber_form.first_name.data,
                                                                new_barber_form.last_name.data))
            return redirect(url_for('barber.index'))

        new_service_form = NewServiceForm()
        if new_service_form.validate_on_submit():
            service = Service(name=new_service_form.name.data,
                              description=new_service_form.description.data,
                              duration=new_service_form.duration.data,
                              price=new_service_form.price.data)
            db.session.add(service)
            db.session.commit()
            flash('{} has been added!'.format(new_service_form.name.data))

        barbers = Barber.query.all()
        services = Service.query.all()

        return render_template('barber/index.html',
                               new_barber_form=new_barber_form,
                               new_service_form=new_service_form,
                               barbers=barbers,
                               services=services)
    else:
        today_reservations = current_user.get_reservations_for_date(date.today()).filter_by(confirmed_status=True)
        return render_template('barber/index.html', today_reservations=today_reservations)


@bp.route('/delete/barber/<id>', methods=['GET', 'POST'])
@login_required
def delete_barber(id):
    barber = Barber.query.filter_by(id=id).first()
    db.session.delete(barber)
    db.session.commit()
    return redirect(url_for('barber.index'))


@bp.route('/delete/service/<id>', methods=['GET', 'POST'])
@login_required
def delete_service(id):
    service = Service.query.filter_by(id=id).first()
    db.session.delete(service)
    db.session.commit()
    return redirect(url_for('barber.index'))

app/templates/barber/base.html
{% extends "base.html" %}

{% block navbar %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{{ url_for('barber.index') }}">
        <i class="fas fa-bold"></i>arbershop <i class="fab fa-amilia"></i>dmin</a>
    <div class="container" id="navbarNav">
        <ul class="nav nav-pills nav-fill">
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('barber.index') }}">HOME</a>
            </li>
        </ul>
        <ul class="nav nav-pills">
            <li>
                <a class="nav-link" href="{{ url_for('auth_barber.logout') }}">
                    <i class="fas fa-sign-out-alt"></i> LOGOUT</a>
            </li>
        </ul>
  </div>
</nav>
{% endblock%}

app/templates/barber/index.html
{% extends "barber/base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}
    <h1>Hi, {{ current_user.first_name }}!</h1>

    {% if current_user.username == 'admin' %}
    <div class="accordion" id="barber_options">
        <div class="card">
            <div class="card-header" id="new_barber">
                <h2 class="mb-0">
                    <a class="btn btn-primary" data-toggle="collapse" href="#new_barber_form" role="button" aria-expanded="false" aria-controls="new_barber_form">
                        New Barber
                    </a>
                </h2>
            </div>

            <div id="new_barber_form" class="collapse" aria-labelledby="new_barber" data-parent="#barber_options">
                <div class="card-body">
                    {{ wtf.quick_form(new_barber_form) }}
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header" id="new_service">
                <h2 class="mb-0">
                    <a class="btn btn-primary" data-toggle="collapse" href="#new_service_form" role="button" aria-expanded="false" aria-controls="new_service_form">
                        New Service
                    </a>
                </h2>
            </div>
            <div id="new_service_form" class="collapse" aria-labelledby="new_service" data-parent="#barbers_options">
                <div class="card-body">
                    {{ wtf.quick_form(new_service_form) }}
                </div>
            </div>
        </div>
    </div>

    <h2>Barbers</h2>
    <table class="table" id="barbers">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Username</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for barber in barbers %}
        <tr>
            <th scope="row">{{ barber.id }}</th>
            <th scope="row">{{ barber.first_name }} {{ barber.last_name }}</th>
            <th scope="row">{{ barber.username }}</th>
            <th scope="row">
                <a class="btn btn-danger"
                   role="button"
                   href="{{ url_for('barber.delete_barber', id=barber.id) }}">
                    Delete
                </a>
            </th>
        </tr>
        {% endfor %}
        </tbody>
    </table>

    <h2>Services</h2>
    <table class="table" id="services">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Name</th>
            <th scope="col">Description</th>
            <th scope="col">Duration (min)</th>
            <th scope="col">Price (RON)</th>
            <th scope="col">Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for service in services %}
        <tr>
            <th scope="row">{{ service.id }}</th>
            <th scope="row">{{ service.name }}</th>
            <th scope="row">{{ service.description }}</th>
            <th scope="row">{{ service.duration }}</th>
            <th scope="row">{{ service.price }}</th>
            <th scope="row">
                <a class="btn btn-danger"
                   role="button"
                   href="{{ url_for('barber.delete_service', id=service.id) }}">
                    Delete
                </a>
            </th>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% else %}
    <h2>Your reservations for today</h2>
    <table class="table" id="reservations">
        <thead>
        <tr>
            <th scope="col">Time</th>
            <th scope="col">Client Name</th>
            <th scope="col">Client Phone</th>
            <th scope="col">Service</th>
            <th scope="col">Duration</th>
            <th scope="col">Confirmation Status</th>
        </tr>
        </thead>
        <tbody>
        {% for reservation in today_reservations %}
        <tr>
            <th scope="row">{{ reservation.reservation_time.strftime('%H:%M') }}</th>
            <th scope="row">{{ reservation.client_first_name }} {{ reservation.client_last_name }}</th>
            <th scope="row">{{ reservation.client_phone }}</th>
            <th scope="row">{{ reservation.get_service() }}</th>
            <th scope="row">{{ reservation.get_duration() }}</th>
            <th scope="row">{{ reservation.confirmed_status }}</th>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    {% endif %}
{% endblock %}